#!/bin/sh
echo "Running pre push commands"

# # Current working directory, should be igx-platform root dir
# CWD=$(pwd);
# echo "Running pre-push script in: $CWD"

# echo "Lint Typescript with npm run lint"
# cd "$CWD/api" && npm run lint;
# cd "$CWD/server" && npm run lint;

# echo "Check for unused code and exports in Typescript with npm run ts-prune"
# cd "$CWD/api" && npm run ts-prune;
# cd "$CWD/server" && npm run ts-prune;

# echo -e "\nScript ran for $(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds.\n";